# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  
  
steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'


task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publish artifacts to Azure Pipelines
- task: DotNetCoreCLI@2
 displayName: 'dotnet publish'
 inputs: 
 command: publish
 publishWebProjects: false
 projects: '**/*.csproj'
 arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# Upload build artifacts
- task: PublishBuildArtifacts@1
 displayName: 'Publish Artifact: drop'
 inputs:
 artifactName: 'AzureDemoPipeline'


- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
