trigger:
 - master
pool:
 vmImage: 'windows-latest'
variables:
 buildConfiguration: 'Release'
steps:
# Download NuGet packages and project-specific tools
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
 inputs:
 command: restore
 projects: '**/*.csproj'

- task: DotNetCoreCLI@2
 displayName: 'dotnet build'
 inputs:
 projects: '**/*.csproj'
 arguments: '--configuration $(buildConfiguration)'
# Run unit tests (e.g., MSTest, xUnit, NUnit)
- task: DotNetCoreCLI@2
 displayName: 'dotnet test'
 inputs:
 command: test
 projects: '**/*.csproj'
 arguments: '--configuration $(buildConfiguration)'
# Publish artifacts to Azure Pipelines
- task: DotNetCoreCLI@2
 displayName: 'dotnet publish'
 inputs: 

 command: publish
 publishWebProjects: false
 projects: '**/*.csproj'
 arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# Upload build artifacts
- task: PublishBuildArtifacts@1
 displayName: 'Publish Artifact: drop'
 inputs:
 artifactName: 'AzureDemoPipeline'
# Deploy a Web Deploy package (ASP.NET)
- task: AzureWebApp@1
 displayName: Azure Web App Deploy
 inputs:
 appType: webApp
 azureSubscription: 'AzureDemoPipelineSC'
 appName: 'AzureDemoAppVitas'
 package: $(Build.ArtifactStagingDirectory)/*.zip

